import localization from './helpers/localization';

const persianLabels = {
    lang: 'EN',
    projectTitle: 'تمرین',
    save: 'ذخیره',
    departments: 'بخش',
    rules: 'سمت',
    procedures: 'پروسه',
    actions: 'فعالیت',
    select__List: '__ را انتخاب نمایید.',
    deleteFaild: 'حذف با مشکل مواجه شد.',
    saveFaild: 'ذخیره اطلاعات با مشکل مواجه شد.',
    loadFaild: 'بازیابی اطلاعات با مشکل مواجه شد.',
    resetForm: 'فرم جدید',
    saveSuccessful: 'فرم بازرسی با موفقیت ذخیره شد.',
    username: 'نام کاربری',
    usernameIsRequired: 'نام کاربری را وارد کنید',
    password: 'کلمه ی عبور',
    passwordIsRequired: 'کلمه ی عبور را وارد کنید',
    login: 'ورود',
    inspectionForm: 'فرم بازرسی',
    logout: 'خروج',
    baseData: 'اطلاعات پایه',
    selectAList: 'یک لیست را انتخاب کنید',
    cancel: 'انصراف',
    ok: 'تائید',
    enterTitle: 'نام',
    enterTitleError: 'نام را وارد کنید.',
    titleExists: 'نام انتخابی موجود می باشد.',
    addNew__: 'تعریف __ جدید',
    Edit__: 'ویرایش __',
    deleteModalTitle__: 'حذف __',
    areYouSureToDelete: 'آیا مطمین هستید؟',
    selectADate: 'تاریخ را انتخاب نمایید',
    selectDate: 'انتخاب تاریخ'
}
const englishLabels = {
    lang: 'فارسی',
    projectTitle: 'LearnReact',
    save: 'Save',
    departments: 'Departments',
    rules: 'Rules',
    procedures: 'Procedures',
    actions: 'Actions',
    select__List: 'Select __ before save.',
    deleteFaild: 'Delete process has been faild.',
    saveFaild: 'Saving process has been faild.',
    loadFaild: 'Loading process has been faild.',
    resetForm: 'New Entry',
    saveSuccessful: 'Inspection has been saved sucessfully.',
    username: 'Username',
    usernameIsRequired: 'Username is required',
    password: 'Password',
    passwordIsRequired: 'Password is required',
    login: 'Login',
    inspectionForm: 'Inspection Form',
    logout: 'Logout',
    baseData: 'Base Data',
    selectAList: 'Select a List',
    cancel: 'Cancel',
    ok: 'OK',
    enterTitle: 'Enter Title',
    enterTitleError: 'Please enter a title.',
    titleExists: 'Title exists.',
    addNew__: 'Add new __',
    Edit__: 'Edit __',
    deleteModalTitle__: 'Delete __',
    areYouSureToDelete: 'Are you sure to delete?',
    selectADate: 'Select a date',
    selectDate: 'Select date'
}

export const labels = localization.isRTL() ? persianLabels : englishLabels;

export const Lists = {
    departments: labels.departments,
    rules: labels.rules,
    procedures: labels.procedures,
    actions: labels.actions
}