export const labels = {
    projectTitle: 'LearnReact',
    save: 'Save',
    departments: 'Departments',
    rules: 'Rules',
    procedures: 'Procedures',
    actions: 'Actions',
    select__List: 'Select __ before save.',
    deleteFaild: 'Delete process has been faild.',
    saveFaild: 'Saving process has been faild.',
    loadFaild: 'Loading process has been faild.',
    resetForm: 'New Entry',
    saveSuccessful: 'Inspection has been saved sucessfully.',
    username: 'Username',
    usernameIsRequired: 'Username is required',
    password: 'Password',
    passwordIsRequired: 'Password is required',
    login: 'Login',
    inspectionForm: 'Inspection Form',
    logout: 'Logout',
    baseData: 'Base Data',
    selectAList: 'Select a List',
    cancel: 'Cancel',
    ok: 'OK',
    enterTitle: 'Enter Title',
    enterTitleError: 'Please enter a title.',
    titleExists: 'Title exists.',
    addNew__: 'Add new __',
    Edit__: 'Edit __',
    deleteModalTitle__: 'Delete __',
    areYouSureToDelete: 'Are you sure to delete?',
    selectADate: 'Select a date',
    selectDate: 'Select date'
};

export const Lists = {
    departments: labels.departments,
    rules: labels.rules,
    procedures: labels.procedures,
    actions: labels.actions
}