const actionTypes = {
    LISTS_LOADING: 'LISTS_LOADING',
    LISTS_LOADED: 'LISTS_LOADED',
    LISTS_HIDE_LOADING: 'LISTS_HIDE_LOADING',
    LISTS_ERROR: 'LISTS_ERROR',
    LISTS_DISMISS_ERROR: 'LISTS_DISMISS_ERROR',

    SLIDER_SAVED: 'SLIDER_SAVED',
    SLIDER_RESET: 'SLIDER_RESET',
    SLIDER_NEXT: 'SLIDER_NEXT',
    SLIDER_PREV: 'SLIDER_PREV',
    SLIDER_SELECTITEM: 'SLIDER_SELECTITEM',

    BASEDATA_CHANGE_SELCTED_LIST: 'BASEDATA_CHANGE_SELCTED_LIST',
    BASEDATA_HIDE_MODAL: 'BASEDATA_HIDE_MODAL',
    BASEDATA_SET_ITEM_TITLE: 'BASEDATA_SET_ITEM_TITLE',
    BASEDATA_ADD_NEW_ITEM: 'BASEDATA_ADD_NEW_ITEM',
    BASEDATA_SAVE_NEW_ITEM: 'BASEDATA_SAVE_NEW_ITEM',
    BASEDATA_UPDATE_ITEM: 'BASEDATA_UPDATE_ITEM',
    BASEDATA_SAVE_UPDATE_ITEM: 'BASEDATA_SAVE_UPDATE_ITEM',
    BASEDATA_SHOW_DELETE_MODAL: 'BASEDATA_SHOW_DELETE_MODAL',
    BASEDATA_HIDE_DELETE_MODAL: 'BASEDATA_HIDE_DELETE_MODAL',
    BASEDATA_DELETE_ITEM: 'BASEDATA_DELETE_ITEM'
};

export default actionTypes;